[workspace]
members = [
    "applications/run-migrations", 
    "applications/frontend-worker",

    "components/common", "applications/gtfs-importer", "components/gtfs",
]

resolver="2"

[profile.dev]
opt-level = 0

[profile.release]
opt-level = 3
