services:
  postgis:
    image: postgis/postgis:latest
    container_name: postgis
    volumes:
      - database:/var/lib/postgresql/data
    env_file: ".env"
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 10s

  x-mobility-map: &mobility-map
    build:
      context: .
      dockerfile: Dockerfile
    env_file: ".env"

  migration:
    <<: *mobility-map
    command: run-migrations
    depends_on:
      postgis:
        condition: service_healthy

  frontend:
    <<: *mobility-map
    command: sleep infinity
    depends_on:
      migration:
        condition: service_completed_successfully

volumes:
  database:
    driver: local
