services:
  postgis:
    image: postgis/postgis:latest
    volumes:
      - database:/var/lib/postgresql/data
    env_file: ".env"
    ports:
      - "5432:5432"
    environment:
      PGUSER: "${POSTGRES_USER}"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 10s

  x-mobility-map: &mobility-map
    build:
      context: .
      dockerfile: Dockerfile
    image: mobility-map
    env_file: ".env"

  x-one-shot: &one-shot
    restart: no
    labels:
      - "com.docker.compose.container-number=0"
      - "com.docker.compose.oneoff=True"
    profiles:
      - one-shot

  migrate-database:
    <<: [*mobility-map, *one-shot]
    depends_on:
      postgis:
        condition: service_healthy

  importer:
    <<: [*mobility-map, *one-shot]
    volumes:
      - ./data:/usr/src/mobility-map/data
      - ./scripts/mobility-flex.lua:/config/mobility-flex.lua
    depends_on:
      postgis:
        condition: service_healthy

volumes:
  database:
    driver: local
