services:
  postgis:
    image: postgis/postgis:latest
    volumes:
      - database:/var/lib/postgresql/data
    env_file: ".env"
    ports:
      - "5432:5432"
    environment:
      PGUSER: "${POSTGRES_USER}"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 10s

  x-mobility-map: &mobility-map
    build:
      context: .
      dockerfile: Dockerfile
    image: mobility-map
    env_file: ".env"

  x-one-shot: &one-shot
    restart: no
    labels:
      - "com.docker.compose.container-number=0"
      - "com.docker.compose.oneoff=True"
    profiles:
      - one-shot

  migration:
    <<: *mobility-map
    command: run-migrations
    depends_on:
      postgis:
        condition: service_healthy

  gtfs-importer:
    <<: [*mobility-map, *one-shot]
    command: run-gtfs-import
    depends_on:
      postgis:
        condition: service_healthy

  osm-importer:
    <<: *one-shot
    image: iboates/osm2pgsql:latest
    env_file: ".env"
    volumes:
      - ./data:/data
      - ./scripts/mobility-flex.lua:/config/mobility-flex.lua
    depends_on:
      postgis:
        condition: service_healthy


  frontend:
    <<: *mobility-map
    command: sleep infinity
    depends_on:
      migration:
        condition: service_completed_successfully

volumes:
  database:
    driver: local
