[package]
name = "run-migrations"
version = "0.0.1"
edition = "2021"

[dependencies]
database-connection = { path = "../../components/database_connection" }
tokio = { version = "1", features = ["full"] }
