#!/bin/bash

set -e

source .env || echo "Could not load .env file. Maybe missing?"

pushd "data/" &> /dev/null

if [ ! -f "${EXTRACT_FILE}" ]; then
  echo "Downloading german OSM extract. This will take a while"
  curl -O "${EXTRACT_URL}"
fi
