#!/bin/bash

source .env || echo "Could not load .env file. Maybe missing?"

docker-compose run --rm osm-importer \
  --database=${DATABASE_URL}         \
  --create                           \
  -v                                 \
  --prefix osm                       \
  --output=flex                      \
  --style=/config/mobility-flex.lua  \
  ${EXTRACT_FILE}
