[package]
name = "analyzers"
version = "0.1.0"
edition = "2021"

[dependencies]
common = { path = "../../components/common" }

tracing.workspace = true
sqlx.workspace    = true

futures = { version = "0.3.31" }
